apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cicd-java-maven
  name: cicd-java-maven
  namespace: cicd-java-maven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-java-maven
  template:
    metadata:
      labels:
        app: cicd-java-maven
    spec:
      containers:
        - name: cicd-java-maven
          image: dash18/cicd-java-maven
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: cicd-java-maven
              protocol: TCP
          volumeMounts:
            - name: logs-volume
              mountPath: /logs.log
      volumes:
        - name: logs-volume
          emptyDir: {}
