apiVersion: v1
kind: Service
metadata:
  labels:
  name: cicd-java-maven
  namespace: cicd-java-maven
spec:
  type: LoadBalancer
  externalIPs:
  - 185.119.196.182
  selector:
    app: cicd-java-maven
  ports:
  - port: 8093
    targetPort: 8080
    protocol: TCP
