apiVersion: v1
kind: Service
metadata:
  labels:
  name: cicd-java-maven
  namespace: cicd-java-maven
spec:
  type: NodePort
  selector:
    app: cicd-java-maven
  ports:
  - port: 8093
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
